#!/usr/bin/env bash
# Script for transfering a file from local machine to remote server

if ['$#' -eq 4] then
	scp -o StrickHostKeyChecking=no -i '$4' '$1' '$3@$2:~/'
elif ['$#' -eq 3]; then
	scp -o StrickHostKeyChecking=no '$1' '$3@$2:~/'
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
