#!/usr/bin/env bash
# Script for installing Nginx and changing the contents of the landing page

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me\/ https:\/\/github.com\/Ddilibe permanent;/" /etc/nginx/sites-enabled/default
service nginx start
