#!/usr/bin/env bash
# Script for installing Nginx and changing the contents of the landing page

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
touch ~/var/www/html/error-page.html
echo "Ceci n'est pas une page" > ~/var/www/html/error-page.html
touch ~/etc/nginx/snippets/error-page.conf
sed -i "s//error_page 404 \/error-page.html;\nlocation=\/error-page.html{\n\t root \/var\/www\/html;\n\tinternal;\n}\n/" /etc/nginx/snippeys/error-page.conf
sed -i "s/\tlisten [::]:80 default_server;/\tlisten [::]:80 default_server;\n\tinclude snippets\/error-page.conf;\n/" /etc/ngnix/sites-avaliable/default
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Ddilibe permanent;}/" /etc/nginx/sites-available/default
service nginx start
